In [13]:
from pathlib import Path
import numpy as np
import pandas as pd
from flycraft.utils.geometry_utils import angle_of_2_velocity
PROJECT_ROOT_DIR = Path().absolute().parent.parent.parent
PROJECT_ROOT_DIR

PosixPath('/home/sen/pythonprojects/fly-craft-examples')

In [46]:
def process_one_file(file_path: Path):
    df = pd.read_csv(file_path)
    df["v_error"] = np.abs(df["v"] - df["achieved v"])
    #df["angle_error"] = df.apply(lambda row: np.abs(angle_of_2_velocity(row["v"], row["mu"], row["chi"], row["achieved v"], row["achieved mu"], row["achieved chi"])), axis=1)
    success_rate = len(df[df["termination"] == "reach target"])/len(df)
    df_timeout = df[(df["termination"] == "timeout")]
    len_of_timeout = len(df_timeout)
    average_angle_error =  sum(df_timeout["error"]) / len_of_timeout
    average_v_error = sum(df_timeout["v_error"]) / len_of_timeout
    return df_timeout,len_of_timeout,average_angle_error,average_v_error,success_rate

In [47]:
files = [
    "logs/cache/LadderRL/eval_error/b_2_one_stage_skip_5_5e6steps_hard_1.csv", 
    "logs/cache/LadderRL/eval_error/b_2_one_stage_skip_5_5e6steps_hard_2.csv", 
    "logs/cache/LadderRL/eval_error/b_2_one_stage_skip_5_5e6steps_hard_3.csv", 
    "logs/cache/LadderRL/eval_error/b_2_one_stage_skip_5_5e6steps_hard_4.csv", 
    "logs/cache/LadderRL/eval_error/b_2_one_stage_skip_5_5e6steps_hard_5.csv", 
]

outcome = []
for index,file in enumerate(files):
    df_timeout,lens,angle_error,v_error,success_rate = process_one_file(PROJECT_ROOT_DIR / file )
    current_outcome = {
        "seed": index+1,
        "len_of_timeout": lens,
        "angle": angle_error,
        "v":v_error,
        "success_rate":success_rate,
    }
    outcome.append(current_outcome)
print(outcome)

# 计算平均值
avg_length = sum(item['len_of_timeout'] for item in outcome) / len(outcome)
avg_angle = sum(item['angle'] for item in outcome) / len(outcome)
avg_velocity = sum(item['v'] for item in outcome) / len(outcome)
avg_successrate = sum(item['success_rate'] for item in outcome) / len(outcome)
print(f"Average length: {avg_length:.2f}")
print(f"Average angle: {avg_angle:.2f}")
print(f"Average velocity: {avg_velocity:.2f}")
print(f"Average successrate: {avg_successrate:.2f}")

[{'seed': 1, 'len_of_timeout': 7058, 'angle': 32.613958880071316, 'v': 15.08698110829009, 'success_rate': 0.2874}, {'seed': 2, 'len_of_timeout': 7410, 'angle': 35.60372361937792, 'v': 14.419363116098655, 'success_rate': 0.2548}, {'seed': 3, 'len_of_timeout': 8102, 'angle': 34.445481576314855, 'v': 11.775064508364215, 'success_rate': 0.1853}, {'seed': 4, 'len_of_timeout': 7331, 'angle': 33.93366729857111, 'v': 10.217779727827763, 'success_rate': 0.2513}, {'seed': 5, 'len_of_timeout': 8246, 'angle': 33.530820948225056, 'v': 13.13899240323808, 'success_rate': 0.1671}]
Average length: 7629.40
Average angle: 34.03
Average velocity: 12.93
Average successrate: 0.23

In [48]:
files = [
    "logs/cache/LadderRL/eval_error/b_05_one_stage_skip_5_5e6steps_hard_1.csv", 
    "logs/cache/LadderRL/eval_error/b_05_one_stage_skip_5_5e6steps_hard_2.csv", 
    "logs/cache/LadderRL/eval_error/b_05_one_stage_skip_5_5e6steps_hard_3.csv", 
    "logs/cache/LadderRL/eval_error/b_05_one_stage_skip_5_5e6steps_hard_4.csv", 
    "logs/cache/LadderRL/eval_error/b_05_one_stage_skip_5_5e6steps_hard_5.csv", 
]


outcome = []
for index,file in enumerate(files):
    df_timeout,lens,angle_error,v_error,success_rate = process_one_file(PROJECT_ROOT_DIR / file )
    current_outcome = {
        "seed": index+1,
        "len_of_timeout": lens,
        "angle": angle_error,
        "v":v_error,
        "success_rate":success_rate,
    }
    outcome.append(current_outcome)
print(outcome)

# 计算平均值
avg_length = sum(item['len_of_timeout'] for item in outcome) / len(outcome)
avg_angle = sum(item['angle'] for item in outcome) / len(outcome)
avg_velocity = sum(item['v'] for item in outcome) / len(outcome)
avg_successrate = sum(item['success_rate'] for item in outcome) / len(outcome)
print(f"Average length: {avg_length:.2f}")
print(f"Average angle: {avg_angle:.2f}")
print(f"Average velocity: {avg_velocity:.2f}")
print(f"Average successrate: {avg_successrate:.2f}")

[{'seed': 1, 'len_of_timeout': 988, 'angle': 31.885686129161883, 'v': 13.09664736640692, 'success_rate': 0.6707}, {'seed': 2, 'len_of_timeout': 782, 'angle': 45.274896653951, 'v': 12.990872161859654, 'success_rate': 0.7187}, {'seed': 3, 'len_of_timeout': 905, 'angle': 57.63737035333369, 'v': 10.85213817833375, 'success_rate': 0.7631}, {'seed': 4, 'len_of_timeout': 3743, 'angle': 47.81822441844351, 'v': 14.904776505878443, 'success_rate': 0.4401}, {'seed': 5, 'len_of_timeout': 1753, 'angle': 39.79794966420413, 'v': 15.545735337183642, 'success_rate': 0.6634}]
Average length: 1634.20
Average angle: 44.48
Average velocity: 13.48
Average successrate: 0.65

In [22]:
df[(df["termination"] == "reach target") & (df["error"] <= 3.0)]

,v,mu,chi,length,termination,achieved v,achieved mu,achieved chi,error,smooth_a_ail,...,smooth2_a_pla,smooth_s_phi,smooth_s_theta,smooth_s_psi,smooth_s_v,smooth_s_mu,smooth_s_chi,smooth_s_p,smooth_s_h,v_error
5,247.618337,-70.258299,-102.618294,84,reach target,247.191692,-68.719217,-96.706655,2.578816,5.917889,...,0.008768,3.503194,0.918853,1.351412,0.548872,0.835303,1.123170,20.405315,12.801346,0.426645
9,240.790761,-64.941203,120.731653,110,reach target,245.367131,-62.159049,119.282214,2.855887,10.960373,...,0.006729,4.276682,1.012320,1.841192,0.441477,0.881663,1.448768,34.558915,15.088853,4.576370
13,282.554931,5.181701,-112.970020,154,reach target,281.333000,2.893893,-114.313078,2.651167,20.543891,...,0.001251,4.817323,0.464624,0.869696,0.522384,0.433752,0.747734,77.328182,7.512152,1.221930
15,225.679148,-73.443517,169.828197,85,reach target,225.945937,-75.235406,177.747452,2.785557,11.414426,...,0.005939,25.210488,1.791821,17.221226,0.354336,1.349761,2.211700,39.343464,13.337423,0.266788
21,118.574275,6.771976,113.252496,135,reach target,117.691021,4.008774,112.394719,2.892131,0.563771,...,0.000169,1.323877,0.681913,0.973774,0.606323,0.287718,0.831172,1.374905,1.167621,0.883254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972,232.827246,21.077237,-105.422607,308,reach target,239.624000,23.795458,-104.475481,2.855677,18.794934,...,0.000517,2.644286,0.199313,0.393259,0.138763,0.148655,0.339488,43.188439,7.054353,6.796754
9977,111.125173,-6.451673,-113.345664,286,reach target,121.089250,-4.616058,-113.984701,1.942683,0.594905,...,0.000184,0.943244,0.808397,0.620529,0.328086,0.263863,0.401571,1.400096,1.235097,9.964076
9979,184.427884,-31.571704,-40.647757,40,reach target,186.054780,-30.188680,-39.509673,1.693132,1.835252,...,0.001445,3.816243,1.110657,1.543540,0.353152,0.737644,0.952316,8.806315,3.410627,1.626896
9981,185.992849,-75.845146,-143.451810,84,reach target,190.017444,-78.759445,-140.515171,2.984010,2.517756,...,0.006013,3.806038,1.190342,11.155804,0.371529,1.205734,1.670123,10.324905,10.337133,4.024595
9996,227.474046,-52.815728,-68.714843,73,reach target,227.425553,-49.861814,-68.205865,2.970956,1.650486,...,0.009579,3.235973,0.916892,1.065896,0.394830,0.709982,0.919258,7.205601,10.261014,0.048494

In [18]:
df[(df["termination"] == "reach target") & (df["error"] > 3.0)]

Empty DataFrame
Columns: [v, mu, chi, length, termination, achieved v, achieved mu, achieved chi, error, smooth_a_ail, smooth_a_ele, smooth_a_rud, smooth_a_pla, smooth2_a_ail, smooth2_a_ele, smooth2_a_rud, smooth2_a_pla, smooth_s_phi, smooth_s_theta, smooth_s_psi, smooth_s_v, smooth_s_mu, smooth_s_chi, smooth_s_p, smooth_s_h, v_error]
Index: []

[0 rows x 26 columns]

In [19]:
df[(df["termination"] == "timeout")]

,v,mu,chi,length,termination,achieved v,achieved mu,achieved chi,error,smooth_a_ail,...,smooth2_a_pla,smooth_s_phi,smooth_s_theta,smooth_s_psi,smooth_s_v,smooth_s_mu,smooth_s_chi,smooth_s_p,smooth_s_h,v_error
0,274.106321,25.014568,-49.006324,399,timeout,255.985557,18.781228,-33.595063,15.583744,32.379587,...,0.000915,5.268234,0.206248,0.310782,0.265318,0.177502,0.090284,100.190057,8.349716,18.120764
1,297.205931,17.936918,160.134557,399,timeout,290.886670,-0.876528,136.448192,29.952953,41.129894,...,0.001140,8.809491,0.499064,0.598420,0.255430,0.219191,0.358524,172.203357,4.172548,6.319260
2,268.117409,-17.258574,152.748452,399,timeout,244.981593,-20.366280,142.099680,10.545058,32.817299,...,0.001844,9.328634,0.995775,0.837967,0.325749,0.402527,0.461381,179.734502,9.529814,23.135817
3,119.668668,12.739131,127.651366,399,timeout,82.054704,-19.955462,88.366177,50.627174,0.525910,...,0.000072,0.727130,0.477450,0.504097,0.341103,0.231135,0.390656,0.630524,1.080334,37.613964
4,223.967417,54.996501,153.992525,399,timeout,201.187642,30.633695,141.286399,25.990783,0.075675,...,0.000130,0.280366,0.139624,0.354306,0.087700,0.126092,0.354214,0.234629,10.137984,22.779774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,162.283891,-18.887883,88.353964,399,timeout,173.708980,-1.862795,83.338367,17.719929,0.246840,...,0.000138,0.612799,0.222197,0.227529,0.105952,0.116116,0.210810,0.931809,1.582656,11.425089
9995,214.350594,-17.557610,-39.690014,399,timeout,228.483653,-0.054110,-40.577076,17.525253,32.211325,...,0.000772,4.670384,0.149332,0.339545,0.112224,0.059816,0.113926,86.391403,0.622639,14.133059
9997,204.646686,11.369208,67.188423,399,timeout,213.358016,1.329565,74.895585,12.621861,0.132847,...,0.001428,0.510335,0.173331,0.209370,0.083101,0.071960,0.187938,0.675341,1.130937,8.711331
9998,182.275923,73.928226,-127.710290,399,timeout,155.379860,22.625197,-156.280543,53.552559,0.270879,...,0.001571,2.002898,0.312491,1.546138,0.176944,0.152631,0.464826,1.010522,9.084482,26.896064
9999,273.961087,-58.116585,26.671366,399,timeout,256.813840,-1.584624,10.785149,57.906242,34.336855,...,0.002939,24.411048,1.949926,1.598740,0.571782,0.757003,0.700042,190.199712,9.476074,17.147247

In [21]:
timeout = df[(df["termination"] == "timeout")]
print(timeout)
print(timeout["error"][0])
average_angle_error = sum(timeout["error"]) / len(timeout)
average_v_error = sum(timeout["v_error"]) / len(timeout)
print(average_angle_error)
print(average_v_error)

               v         mu         chi  length termination  achieved v  \
0     274.106321  25.014568  -49.006324     399     timeout  255.985557
1     297.205931  17.936918  160.134557     399     timeout  290.886670
2     268.117409 -17.258574  152.748452     399     timeout  244.981593
3     119.668668  12.739131  127.651366     399     timeout   82.054704
4     223.967417  54.996501  153.992525     399     timeout  201.187642
...          ...        ...         ...     ...         ...         ...
9994  162.283891 -18.887883   88.353964     399     timeout  173.708980
9995  214.350594 -17.557610  -39.690014     399     timeout  228.483653
9997  204.646686  11.369208   67.188423     399     timeout  213.358016
9998  182.275923  73.928226 -127.710290     399     timeout  155.379860
9999  273.961087 -58.116585   26.671366     399     timeout  256.813840

      achieved mu  achieved chi      error  smooth_a_ail  ...  smooth2_a_pla  \
0       18.781228    -33.595063  15.583744     32.379587  ...       0.000915
1       -0.876528    136.448192  29.952953     41.129894  ...       0.001140
2      -20.366280    142.099680  10.545058     32.817299  ...       0.001844
3      -19.955462     88.366177  50.627174      0.525910  ...       0.000072
4       30.633695    141.286399  25.990783      0.075675  ...       0.000130
...           ...           ...        ...           ...  ...            ...
9994    -1.862795     83.338367  17.719929      0.246840  ...       0.000138
9995    -0.054110    -40.577076  17.525253     32.211325  ...       0.000772
9997     1.329565     74.895585  12.621861      0.132847  ...       0.001428
9998    22.625197   -156.280543  53.552559      0.270879  ...       0.001571
9999    -1.584624     10.785149  57.906242     34.336855  ...       0.002939

      smooth_s_phi  smooth_s_theta  smooth_s_psi  smooth_s_v  smooth_s_mu  \
0         5.268234        0.206248      0.310782    0.265318     0.177502
1         8.809491        0.499064      0.598420    0.255430     0.219191
2         9.328634        0.995775      0.837967    0.325749     0.402527
3         0.727130        0.477450      0.504097    0.341103     0.231135
4         0.280366        0.139624      0.354306    0.087700     0.126092
...            ...             ...           ...         ...          ...
9994      0.612799        0.222197      0.227529    0.105952     0.116116
9995      4.670384        0.149332      0.339545    0.112224     0.059816
9997      0.510335        0.173331      0.209370    0.083101     0.071960
9998      2.002898        0.312491      1.546138    0.176944     0.152631
9999     24.411048        1.949926      1.598740    0.571782     0.757003

      smooth_s_chi  smooth_s_p  smooth_s_h    v_error
0         0.090284  100.190057    8.349716  18.120764
1         0.358524  172.203357    4.172548   6.319260
2         0.461381  179.734502    9.529814  23.135817
3         0.390656    0.630524    1.080334  37.613964
4         0.354214    0.234629   10.137984  22.779774
...            ...         ...         ...        ...
9994      0.210810    0.931809    1.582656  11.425089
9995      0.113926   86.391403    0.622639  14.133059
9997      0.187938    0.675341    1.130937   8.711331
9998      0.464826    1.010522    9.084482  26.896064
9999      0.700042  190.199712    9.476074  17.147247

[7058 rows x 26 columns]
15.583744014540128
32.613958880071316
15.08698110829009